# Generated by Django 3.1.5 on 2021-05-04 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StockPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('Company', models.CharField(default='Unknown', max_length=25, verbose_name='Company')),
                ('Times', models.DateField(default='Unknown', verbose_name='Times')),
                ('Price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Price')),
            ],
        ),
        migrations.CreateModel(
            name='TradeField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('User', models.CharField(default='Unknown', max_length=50, verbose_name='User')),
                ('Company', models.CharField(default='Unknown', max_length=25, verbose_name='Company')),
                ('TradePrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='TradePrice')),
                ('TradeTime', models.DateField(auto_now_add=True, verbose_name='TradeTime')),
                ('ForSell', models.BooleanField(default=True, verbose_name='ForSell')),
                ('ForBuy', models.BooleanField(default=True, verbose_name='ForBuy')),
                ('BuyPrice', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='BuyPrice')),
            ],
        ),
    ]
