# Generated by Django 3.1.5 on 2021-05-04 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradefield',
            name='ForBuy',
            field=models.BooleanField(default=False, verbose_name='ForBuy'),
        ),
        migrations.AlterField(
            model_name='tradefield',
            name='ForSell',
            field=models.BooleanField(default=False, verbose_name='ForSell'),
        ),
    ]
