# Generated by Django 3.1.5 on 2021-05-05 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_auto_20210504_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockprice',
            name='initial_share',
            field=models.PositiveIntegerField(default=100, max_length=1000, verbose_name='initial'),
        ),
    ]
