# Generated by Django 3.1.5 on 2021-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_stockprice_initial_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='initial_share',
            field=models.PositiveIntegerField(default=100, verbose_name='initial'),
        ),
    ]
