# Generated by Django 3.1.5 on 2021-05-05 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_auto_20210505_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockprice',
            name='Price',
            field=models.FloatField(default=0.0, verbose_name='Price'),
        ),
    ]
