# Generated by Django 3.1.5 on 2021-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_auto_20210505_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tradefield',
            name='BuyPrice',
            field=models.FloatField(default=0.0, verbose_name='BuyPrice'),
        ),
        migrations.AlterField(
            model_name='tradefield',
            name='TradePrice',
            field=models.FloatField(default=0.0, verbose_name='TradePrice'),
        ),
    ]
