# Generated by Django 3.1.5 on 2021-05-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='AAPL_num',
            field=models.PositiveIntegerField(default=0, max_length=1000, verbose_name='AAPL_num'),
        ),
        migrations.AddField(
            model_name='account',
            name='Google_num',
            field=models.PositiveIntegerField(default=0, max_length=1000, verbose_name='Google_num'),
        ),
    ]
