# Generated by Django 3.1.5 on 2021-05-04 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20210504_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='AAPL_num',
        ),
        migrations.RemoveField(
            model_name='account',
            name='Google_num',
        ),
        migrations.AddField(
            model_name='account',
            name='AAPL',
            field=models.PositiveIntegerField(default=0, max_length=1000, verbose_name='AAPL'),
        ),
        migrations.AddField(
            model_name='account',
            name='Google',
            field=models.PositiveIntegerField(default=0, max_length=1000, verbose_name='Google'),
        ),
    ]
