# Generated by Django 3.1.5 on 2021-05-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20210504_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='AAPL',
            field=models.PositiveIntegerField(default=0, verbose_name='AAPL'),
        ),
        migrations.AlterField(
            model_name='account',
            name='Google',
            field=models.PositiveIntegerField(default=0, verbose_name='Google'),
        ),
    ]
