# Generated by Django 3.1.5 on 2021-05-05 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210505_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='money',
            field=models.FloatField(default=1000.0, verbose_name='Money'),
        ),
    ]
